import { countries } from "../../../data/data";
import { getSelectFormattedData, formatDate } from "../../../hooks/general";
import { includes } from "../../../hooks/polyfills";
import { FormField } from "../../../hooks/types";

export const LeadFormType: FormField[] = [
  { name: "id", type: "text", required: false, label: "ID", isDisabled: true },
  {
    name: "title",
    type: "text",
    required: false,
    label: "Title",
    isDisabled: false,
  },
  {
    name: "firstName",
    type: "text",
    required: true,
    label: "First Name",
    isDisabled: false,
  },
  {
    name: "lastName",
    type: "text",
    required: true,
    label: "Last Name",
    isDisabled: false,
  },
  {
    name: "dateOfBirth",
    type: "date",
    required: true,
    label: "Date of Birth",
    isDisabled: false,
  },
  {
    name: "mobile",
    type: "text",
    required: true,
    label: "Mobile",
    isDisabled: false,
  },
  {
    name: "email",
    type: "email",
    required: true,
    label: "Email",
    isDisabled: false,
  },
  {
    name: "loanAmount",
    type: "text",
    required: false,
    label: "Loan Amount",
    isDisabled: false,
  },
  {
    name: "weeklyPayment",
    type: "text",
    required: false,
    label: "Weekly Payment",
    isDisabled: false,
  },
  {
    name: "otpVerified",
    type: "text",
    required: false,
    label: "Verified",
    isDisabled: false,
  },
  {
    name: "termYears",
    type: "text",
    required: false,
    label: "Term (Years)",
    isDisabled: false,
  },
  {
    name: "maritalStatus",
    type: "text",
    required: false,
    label: "Marital Status",
    isDisabled: false,
  },
  {
    name: "noOfDependents",
    type: "text",
    required: false,
    label: "No. of Dependents",
    isDisabled: false,
  },
  {
    name: "drivingLicenceType",
    type: "text",
    required: false,
    label: "Driving Licence Type",
    isDisabled: false,
  },
  {
    name: "preferredContact",
    type: "text",
    required: false,
    label: "Preferred Contact",
    isDisabled: false,
  },
  {
    name: "streetAddress",
    type: "text",
    required: false,
    label: "Street Address",
    isDisabled: false,
  },
  {
    name: "addressLine2",
    type: "text",
    required: false,
    label: "Address Line 2",
    isDisabled: false,
  },
  {
    name: "city",
    type: "text",
    required: false,
    label: "City",
    isDisabled: false,
  },
  {
    name: "postalCode",
    type: "text",
    required: false,
    label: "Postal Code",
    isDisabled: false,
  },
  {
    name: "propertyStatus",
    type: "text",
    required: false,
    label: "Property Status",
    isDisabled: false,
  },
  {
    name: "timeAtPropertyYears",
    type: "text",
    required: false,
    label: "Time at Property (Years)",
    isDisabled: false,
  },
  {
    name: "timeAtPropertyMonths",
    type: "text",
    required: false,
    label: "Time at Property (Months)",
    isDisabled: false,
  },
  {
    name: "monthlyCost",
    type: "text",
    required: false,
    label: "Monthly Cost",
    isDisabled: false,
  },
  {
    name: "region",
    type: "text",
    required: false,
    label: "Region",
    isDisabled: false,
  },
  {
    name: "residentialStatus",
    type: "text",
    required: false,
    label: "Residential Status",
    isDisabled: false,
  },
  {
    name: "employmentStatus",
    type: "text",
    required: false,
    label: "Employment Status",
    isDisabled: false,
  },
  {
    name: "jobTitle",
    type: "text",
    required: false,
    label: "Job Title",
    isDisabled: false,
  },
  {
    name: "timeAtEmployerYears",
    type: "text",
    required: false,
    label: "Time at Employer (Years)",
    isDisabled: false,
  },
  {
    name: "timeAtEmployerMonths",
    type: "text",
    required: false,
    label: "Time at Employer (Months)",
    isDisabled: false,
  },
  {
    name: "createdAt",
    type: "date",
    required: false,
    label: "Created At",
    isDisabled: false,
  },
  {
    name: "status",
    type: "select",
    required: false,
    label: "Status",
    isDisabled: true,
    options: [
      { value: "Select Status", label: "Select Status" },
      { value: "Eligible", label: "Eligible" },
      { value: "Not Eligible", label: "Not Eligible" },
      { value: "Pending", label: "Pending" },
    ],
  },
];
