import { countries, bankNames } from "../../../data/data";
import { getSelectFormattedData } from "../../../hooks/general";
import { includes } from "../../../hooks/polyfills";
import { FormField } from "../../../hooks/types";

export const LoanFormType: FormField[] = [
  {
    name: "id",
    type: "number",
    required: true,
    label: "Loan Query ID",
    isDisabled: true,
  },
  {
    name: "loanQueryNumber",
    type: "text",
    required: true,
    label: "Loan Query Number",
    isDisabled: true,
  },
  {
    name: "userId",
    type: "number",
    required: true,
    label: "User ID",
    isDisabled: true,
  },
  {
    name: "leadId",
    type: "number",
    required: false,
    label: "Lead ID",
    isDisabled: true,
  },
  {
    name: "userType",
    type: "text",
    required: true,
    label: "User Type",
    isDisabled: true,
  },
  {
    name: "loanAppliedFor",
    type: "text",
    required: true,
    label: "Loan Applied For",
    isDisabled: true,
  },
  {
    name: "purchasePrice",
    type: "number",
    required: true,
    label: "Purchase Price",
    isDisabled: true,
  },
  {
    name: "loanTerm",
    type: "text",
    required: false,
    label: "Loan Term",
    isDisabled: true,
  },
  {
    name: "paymentFrequency",
    type: "text",
    required: true,
    label: "Payment Frequency",
    isDisabled: true,
  },
  {
    name: "depositAmount",
    type: "number",
    required: true,
    label: "Deposit Amount",
    isDisabled: true,
  },
  {
    name: "make",
    type: "text",
    required: true,
    label: "Vehicle Make",
    isDisabled: true,
  },
  {
    name: "model",
    type: "text",
    required: true,
    label: "Vehicle Model",
    isDisabled: true,
  },
  {
    name: "modelYear",
    type: "number",
    required: true,
    label: "Vehicle Model Year",
    isDisabled: true,
  },
  {
    name: "applicationType",
    type: "text",
    required: true,
    label: "Application Type",
    isDisabled: true,
  },
  {
    name: "maritalStatus",
    type: "text",
    required: true,
    label: "Marital Status",
    isDisabled: true,
  },
  {
    name: "dependents",
    type: "text",
    required: true,
    label: "Number of Dependents",
    isDisabled: true,
  },
  {
    name: "driverLicenseType",
    type: "text",
    required: true,
    label: "Driver License Type",
    isDisabled: true,
  },
  {
    name: "driverLicenseNumber",
    type: "text",
    required: true,
    label: "Driver License Number",
    isDisabled: true,
  },
  {
    name: "driverLicenseVersion",
    type: "text",
    required: true,
    label: "Driver License Version",
    isDisabled: true,
  },

  {
    name: "homeOwnership",
    type: "text",
    required: true,
    label: "Home Ownership",
    isDisabled: true,
  },

  {
    name: "employerName",
    type: "text",
    required: false,
    label: "Employer Name",
    isDisabled: true,
  },
  {
    name: "occupation",
    type: "text",
    required: false,
    label: "Occupation",
    isDisabled: true,
  },
  {
    name: "employmentType",
    type: "text",
    required: false,
    label: "Employment Type",
    isDisabled: true,
  },
  {
    name: "timeInThisJob",
    type: "number",
    required: false,
    label: "Time in Current Job",
    isDisabled: true,
  },
  {
    name: "paidFrequency",
    type: "text",
    required: false,
    label: "Salary Payment Frequency",
    isDisabled: true,
  },
  {
    name: "takeHomeIncome",
    type: "number",
    required: false,
    label: "Take Home Income",
    isDisabled: true,
  },
  {
    name: "partnerPaidFrequency",
    type: "text",
    required: false,
    label: "Partner Paid Frequency",
    isDisabled: true,
  },
  {
    name: "partnerTakeHomeIncome",
    type: "number",
    required: false,
    label: "Partner Take Home Income",
    isDisabled: true,
  },
  {
    name: "otherIncome",
    type: "checkbox",
    required: false,
    label: "Other Income",
    isDisabled: true,
  },
  {
    name: "companyName",
    type: "text",
    required: true,
    label: "Company Name",
    isDisabled: true,
  },
  {
    name: "companyAddress",
    type: "text",
    required: true,
    label: "Company Address",
    isDisabled: true,
  },
  {
    name: "typeOfEmployee",
    type: "text",
    required: false,
    label: "Type of Employee",
    isDisabled: true,
  },
  {
    name: "dateOfJoining",
    type: "date",
    required: true,
    label: "Date of Joining",
    isDisabled: true,
  },
  {
    name: "status",
    type: "text",
    required: true,
    label: "Status",
    isDisabled: true,
  },
  {
    name: "status",
    type: "select",
    required: false,
    label: "Status",
    options: [
      { value: "Approved", label: "Approved" },
      { value: "Disapproved", label: "Disapproved" },
      { value: "Pending", label: "Pending" },
      { value: "In Progress", label: "In Progress" },
    ],
  },
  {
    name: "rentAgreement",
    type: "link",
    required: false,
    label: "Rent Agreement",
    isDisabled: true,
  },
  {
    name: "comments",
    type: "textarea",
    required: false,
    label: "Comments",
    isDisabled: true,
  },
  {
    name: "driverLicenseDocument",
    type: "link",
    required: false,
    label: "Driver License Document",
    isDisabled: true,
  },

];
