import { countries } from "../../../data/data";
import { formatDate, getSelectFormattedData } from "../../../hooks/general";
import { includes } from "../../../hooks/polyfills";
import { FormField } from "../../../hooks/types";


export const userFormType: FormField[] = [
  {
    name: "name",
    type: "text",
    required: true,
    label: "User Name",
    placeholder: "Enter user name",
  },
  {
    name: "mobileNo",
    maxLength: 15,
    label: "Mobile Number",
    type: "stringNumeric",
    placeholder: "Enter your mobile number",
    required: true,
  },
  {
    name: "altMobileNo",
    maxLength: 15,
    label: "Alternate Mobile Number",
    type: "stringNumeric",
    placeholder: "Enter your alternate mobile number",
  },
  {
    name: "email",
    type: "email",
    label: "Email",
    required: true,
    placeholder: "Enter your email",
    validation: (value) => (includes(value, "@") ? null : "Invalid email"),
  },
  {
    name: "birthDate",
    label: "Date of Birth",
    type: "date",
    required: false,
    maxDate: formatDate(new Date()),
    placeholder: "Enter date of birth",
  },
  {
    name: "joiningDate",
    label: "Joining Date",
    type: "date",
    required: false,
    placeholder: "Enter join date",
  },
  {
    name: "leavingDate",
    label: "Leaving Date",
    type: "date",
    required: false,
    placeholder: "Enter date of leaving",
  },
  {
    name: "role",
    label: "User Role",
    type: "select",
    required: true,
    placeholder: "Select user role",
    options: [],
  },
  {
    type: "text",
    name: "qualification",
    label: "User's Qualification",
    placeholder: "Enter user's Qualification",
  },
  {
    name: "panNo",
    type: "text",
    label: "User's PAN Number",
    placeholder: "Enter user's PAN Number",
  },
  {
    name: "aadhaarNo",
    type: "text",
    label: "User's Aadhar Number",
    placeholder: "Enter user's Aadhar Number",
  },
  {
    name: "familyRefInfo",
    type: "text",
    label: "User's Family Reference Information",
    placeholder: "Enter user's Family Reference Information",
  },
  {
    name: "status",
    label: "Do you want to activate this user?",
    type: "choose",
    required: false,
  },
  { type: "br", name: "Salary", label: "Salary Details", widthFull: true },
  {
    name: "basic",
    maxLength: 10,
    type: "number",
    label: "Basic Salary",
    placeholder: "Enter basic Salary",
  },
  {
    name: "hra",
    maxLength: 10,
    type: "number",
    label: "Home Rental Allowance",
    placeholder: "Enter Home Rental Allowance",
  },
  {
    name: "conveyance",
    maxLength: 10,
    type: "number",
    label: "Conveyance",
    placeholder: "Enter conveyance",
  },
  { type: "br", name: "Address", label: "Address Details", widthFull: true },
  {
    type: "text",
    name: "line1",
    label: "Address 1",
    required: true,
    placeholder: "Enter Line 1",
  },
  {
    name: "street",
    type: "text",
    label: "Street Address",
    placeholder: "Enter street address",
  },
  {
    name: "city",
    type: "text",
    label: "City",
    required: true,
    placeholder: "Enter city",
  },
  {
    name: "state",
    type: "text",
    required: true,
    label: "State",
    placeholder: "Enter state",
  },
  {
    name: "pinCode",
    maxLength: 15,
    label: "Pin Code",
    required: true,
    type: "stringNumeric",
    placeholder: "Enter pin code",
  },
  {
    type: "select",
    name: "country",
    required: true,
    label: "Country",
    placeholder: "Select Country",
    options: getSelectFormattedData(countries),
  },
  {
    name: "landmark",
    type: "text",
    label: "Landmark",
    placeholder: "Enter landmark",
  },
  { type: "br", name: "upload", label: "Upload Documents", widthFull: true },
  {
    name: "profilePic",
    label: "Profile Image",
    type: "file",
    required: true,
  },
  {
    name: "panCardDoc",
    label: "Pan Card Image",
    type: "file",
  },
  {
    name: "aadhaarCardDoc",
    label: "Aadhar Card Image",
    type: "file",
  },
  {
    name: "otherDoc",
    label: "Other Documents Image",
    type: "file",
  },
];
